[package]
name = "power_monitor"
version = "0.1.0"
authors = ["Mark van Cuijk <mark@van-cuijk.nl>"]

[dependencies]
lazy_static = "1.1.0"
regex = "1"

[dependencies.crc]
git = "https://github.com/mrhooray/crc-rs"
